/*****************************************************************************/
/*                                                                           */
/* FILENAME                                                                  */
/* 	 filtercoefficients.h                                                    */
/*                                                                           */
/* DESCRIPTION                                                               */
/*   contains the FIR filter coefficients                                    */
/*                                                                           */
/* REVISION                                                                  */
/*   Revision: 2.00	                                                         */
/*   Author  : Marc Geilen                                                   */
/*---------------------------------------------------------------------------*/
/*                                                                           */
/* HISTORY                                                                   */
/*   Revision 1.00                                                           */
/*   1st June 2016.                                                          */
/*   Revision 2.00                                                           */
/*   7th June 2019.                                                         */
/*                                                                           */
/*****************************************************************************/

#ifndef FILTERCOEFFICIENTS_H_
#define FILTERCOEFFICIENTS_H_

#include <stdint.h>

/*****************************************************************************/
/* Low Pass Filter Coefficients                                              */
/*****************************************************************************/

// The code below is automatically generated by the Matlab script firdesign.m
// It is an 60th order (length 61) low pass FIR filter with cutoff frequency 1000Hz.
// It is for a digital system with a sampling frequency of 48kHz.
// The generated filter coefficients are the integer representations of fixed point
// numbers in the representation: Q(16,16).
#define FIR_FILTER_LENGTH 61
#define FIR_FRACTIONAL_BITS 16
const int16_t FIRFilterCoefficients[FIR_FILTER_LENGTH] = {
	-42, -39, -36, -32, -27, -17, 0, 25, 
	61, 110, 173, 253, 349, 463, 595, 743, 
	907, 1083, 1270, 1464, 1662, 1859, 2051, 2233, 
	2402, 2553, 2682, 2786, 2863, 2909, 2925, 2909, 
	2863, 2786, 2682, 2553, 2402, 2233, 2051, 1859, 
	1662, 1464, 1270, 1083, 907, 743, 595, 463, 
	349, 253, 173, 110, 61, 25, 0, -17, 
	-27, -32, -36, -39, -42
};

#endif /*FILTERCOEFFICIENTS_H_*/
