/*****************************************************************************/
/*                                                                           */
/* FILENAME                                                                  */
/* 	 filtercoefficients.h                                                    */
/*                                                                           */
/* DESCRIPTION                                                               */
/*   contains the FIR filter coefficients                                    */
/*                                                                           */
/* REVISION                                                                  */
/*   Revision: 2.00	                                                         */
/*   Author  : Marc Geilen                                                   */
/*---------------------------------------------------------------------------*/
/*                                                                           */
/* HISTORY                                                                   */
/*   Revision 1.00                                                           */
/*   1st June 2016.                                                          */
/*   Revision 2.00                                                           */
/*   7th June 2019.                                                         */
/*                                                                           */
/*****************************************************************************/

#ifndef FILTERCOEFFICIENTS_H_
#define FILTERCOEFFICIENTS_H_

/*****************************************************************************/
/* Low Pass Filter Coefficients                                              */
/*****************************************************************************/

// The code below is automatically generated by the Matlab script firdesign.m
// It is an 24th order (length 25) low pass FIR filter with cutoff frequency 1000Hz.
// It is for a digital system with a sampling frequency of 48kHz.
// The generated filter coefficients are the integer representations of fixed point
// numbers in the representation: Q(8,8).
#define FIR_FILTER_LENGTH 25
#define FIR_FRACTIONAL_BITS 8
const int16_t FIRFilterCoefficients[FIR_FILTER_LENGTH] = {
	1, 1, 2, 4, 5, 8, 10, 13,
	15, 18, 19, 21, 21, 21, 19, 18,
	15, 13, 10, 8, 5, 4, 2, 1,
	1
};


#endif /*FILTERCOEFFICIENTS_H_*/
