/*****************************************************************************/
/*                                                                           */
/* FILENAME                                                                  */
/* 	 filtercoefficients.h                                                    */
/*                                                                           */
/* DESCRIPTION                                                               */
/*   contains the FIR filter coefficients                                    */
/*                                                                           */
/* REVISION                                                                  */
/*   Revision: 2.00	                                                         */
/*   Author  : Marc Geilen                                                   */
/*---------------------------------------------------------------------------*/
/*                                                                           */
/* HISTORY                                                                   */
/*   Revision 1.00                                                           */
/*   1st June 2016.                                                          */
/*   Revision 2.00                                                           */
/*   7th June 2019.                                                         */
/*                                                                           */
/*****************************************************************************/

#ifndef FILTERCOEFFICIENTS_H_
#define FILTERCOEFFICIENTS_H_

#include <stdint.h>

/*****************************************************************************/
/* Low Pass Filter Coefficients                                              */
/*****************************************************************************/

// The code below is automatically generated by the Matlab script firdesign.m
// It is an 90th order (length 91) low pass FIR filter with cutoff frequency 1000Hz.
// It is for a digital system with a sampling frequency of 48kHz.
// The generated filter coefficients are the integer representations of fixed point
// numbers in the representation: Q(16,16).
#define FIR_FILTER_LENGTH 91
#define FIR_FRACTIONAL_BITS 16
const int16_t FIRFilterCoefficients[FIR_FILTER_LENGTH] = {
	-14, -19, -25, -32, -39, -49, -59, -71, 
	-84, -97, -111, -124, -135, -145, -151, -152, 
	-148, -137, -117, -89, -50, 0, 62, 136, 
	223, 322, 434, 557, 691, 835, 986, 1144, 
	1306, 1469, 1633, 1793, 1948, 2094, 2230, 2354, 
	2462, 2554, 2626, 2680, 2712, 2723, 2712, 2680, 
	2626, 2554, 2462, 2354, 2230, 2094, 1948, 1793, 
	1633, 1469, 1306, 1144, 986, 835, 691, 557, 
	434, 322, 223, 136, 62, 0, -50, -89, 
	-117, -137, -148, -152, -151, -145, -135, -124, 
	-111, -97, -84, -71, -59, -49, -39, -32, 
	-25, -19, -14
};




#endif /*FILTERCOEFFICIENTS_H_*/
